sudo: false
language: node_js
node_js:
    - "5.2"
    - "4.2"
script: npm run-script travis

before_install:
    - '[ "${TRAVIS_NODE_VERSION}" != "0.10"  ] || npm install -g npm'

notifications:
    email: false

